# Generated by Django 5.1.3 on 2024-11-21 18:06

import LLM_interaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserUsageHistory",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("input_tokens_number", models.IntegerField()),
                ("output_tokens_number", models.IntegerField()),
                ("index_name", models.UUIDField()),
                (
                    "creation_date",
                    models.DateTimeField(default=LLM_interaction.models.get_uae_time),
                ),
            ],
        ),
    ]
